name = "blog"
compatibility_date = "2026-06-07"

routes = [
  { pattern = "aufb.de", custom_domain = true },
  { pattern = "www.aufb.de", custom_domain = true },
]

[assets]
directory = "./dist"

[env.dev]
routes = [
  { pattern = "dev.aufb.de", custom_domain = true },
]

[env.dev.assets]
directory = "./dist"
