name = "blog"
compatibility_date = "2026-06-07"

routes = [
  { pattern = "aufb.de", custom_domain = true },
  { pattern = "www.aufb.de", custom_domain = true },
]

[assets]
directory = "./dist"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1



[env.dev]
routes = [
  { pattern = "dev.aufb.de", custom_domain = true },
]

[env.dev.assets]
directory = "./dist"
