name = "blog"
main = "src/worker.ts"
compatibility_date = "2026-06-07"

routes = [
  { pattern = "aufb.de", custom_domain = true },
  { pattern = "www.aufb.de", custom_domain = true },
]

[assets]
directory = "./dist"
binding = "ASSETS"

[[send_email]]
name = "EMAIL"

[[d1_databases]]
binding = "DB"
database_name = "blog-subscribers"
database_id = "32734eed-5274-4957-a78b-c4f226c28a9e"
migrations_dir = "./migrations"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1



[env.dev]
routes = [
  { pattern = "dev.aufb.de", custom_domain = true },
]

[env.dev.assets]
directory = "./dist"
